name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testnet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
      
    - name: Set up Go 1.23.0
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Install JQ
      run: sudo apt-get install jq

    - name: Build dependencies
      run: ./build-dependencies.sh
      
    - name: Start Node
      run: |
        ./node.sh &
        sleep 60

    - name: Run Health check
      run: ./healthcheck.sh